# Generated by Django 5.0.6 on 2024-11-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
