# Generated by Django 5.0.6 on 2023-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='core.coupon'),
        ),
    ]
