# Generated by Django 5.0.6 on 2023-09-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cartorder_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
