# Generated by Django 5.0.6 on 2024-11-29 10:54

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', blank=True, length=4, max_length=10, null=True, prefix='sku'),
        ),
    ]
