# Generated by Django 5.0.6 on 2024-11-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_cartorder_oid_alter_cartorder_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='sku',
        ),
    ]
